spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:ramenddang;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  data:
    redis:
      host: localhost
      port: 6379

  profile:
    image:
      dir: "src/main/resources/static/profiles/"
      url: "/profiles/"

  ramen:
    image:
      dir: "src/main/resources/static/ramen/"
      url: "/ramen/"

  review:
    image:
      dir: "src/main/resources/static/review/"
      url: "/review/"
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    url: "jdbc:mysql://localhost/ramenddang"
    username: "root"
    password: "Abcd1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        sql: debug
    org.springframework.cache: trace

profile:
  image:
    dir: "src/main/resources/static/profiles/"
    url: "/profiles/"

ramen:
  image:
    dir: "src/main/resources/static/ramen/"
    url: "/ramen/"

review:
  image:
    dir: "src/main/resources/static/review/"
    url: "/review/"